spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.mybatis: INFO
    org.thymeleaf: INFO
    org.quartz.core: INFO
    org.hibernate.SQL: INFO
    org.h2.server.web: INFO
    com.sixessense.admin: INFO
    org.springframework.web: INFO